### ISSUE TITLE
图标内敛写法

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/CSS#1]
# 将小图标做成base64的格式，然后直接放置于css
css 写法，把小图片做成内联的样式  484bt

``` css
img{
    background-image:url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAA21BMVEUAAABaPxf///9FLxAHAgAEAAAJBAADAAAZDwQjEgEmEgBdPxbEjjSrfTCidi3Vnz8PbZoPfrUmlNRFamlMp+CNh1i2l2i3kEK3lUvCiy3GnlDJm0zJol/Kq3bNupzPnDrPoVnUokTV1dPW19fXsGraqEDe39/isULjr0bjtkvmuUvoxl3pvlXq6+vt3cPvzmnx03vz1or0xlr10V322mb253T31GP39/f41lz43XH58+r6z2D61Fz65Jr94XD+zVf+6q//2WL/3m3/32v/33j/5Gb/63n/8K3///8gMwmgAAAAEHRSTlMAAAAFGR8hJjRZXHqsxszzUE1OxQAAAIJJREFUGNNjYEIDDJgCgsgALOCBAFABIRiACYjAgAeqFis9BQkesIAyECjJyUqrGLrJgwXUgEBG3dbB3cWCHyygCwSqWlIGNq463GABcyDQ0JTUdrZTZIUbKmZvpm9sKcoMd6mAuKOJqZMwI9wvDBy8RtZ8LAwIAQY2Ti52BgZM3wIAXegY5KkkissAAAAASUVORK5CYII=");
    width:20px;
    height:20px;
    background-repeat: no-repeat;
}

```

img标签的写法

``` html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAA21BMVEUAAABaPxf///9FLxAHAgAEAAAJBAADAAAZDwQjEgEmEgBdPxbEjjSrfTCidi3Vnz8PbZoPfrUmlNRFamlMp+CNh1i2l2i3kEK3lUvCiy3GnlDJm0zJol/Kq3bNupzPnDrPoVnUokTV1dPW19fXsGraqEDe39/isULjr0bjtkvmuUvoxl3pvlXq6+vt3cPvzmnx03vz1or0xlr10V322mb253T31GP39/f41lz43XH58+r6z2D61Fz65Jr94XD+zVf+6q//2WL/3m3/32v/33j/5Gb/63n/8K3///8gMwmgAAAAEHRSTlMAAAAFGR8hJjRZXHqsxszzUE1OxQAAAIJJREFUGNNjYEIDDJgCgsgALOCBAFABIRiACYjAgAeqFis9BQkesIAyECjJyUqrGLrJgwXUgEBG3dbB3cWCHyygCwSqWlIGNq463GABcyDQ0JTUdrZTZIUbKmZvpm9sKcoMd6mAuKOJqZMwI9wvDBy8RtZ8LAwIAQY2Ti52BgZM3wIAXegY5KkkissAAAAASUVORK5CYII=">
```
