### ISSUE TITLE
css优先级

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/CSS#10]
# CSS的优先性

> 行内样式 > id样式 > class样式 > 标签名样式
### 比如有一个元素
```html
　<div id="ID" class="CLASS" style="color:black;"></div>
```
### 行内样式是最优先的，然后其他设置的优先性，从低到高依次为：

```
div < .class < div.class < #id < div#id < #id.class < div#id.class
```
# 经测试，优先级由高到低排列为
```css
	/*DOM+类+ID*/
	div#id.class{
		background:gray;
	}
	/*类+ID*/
	#id.class{
		background:black;
	}
	/*DOM+ID*/
	div#ID {	
		background:red;
	}
	/*单ID*/
	#ID{
		background:orange;
	}
	/*DOM + 类*/
	div.CLASS {
		background:pink;
	}
	/*单类*/
	.CLASS {
		background:gray;
	}
	/*单DOM*/
	div {
		background:blue;
	}

```
# 多层嵌套规则同上
> 优先级id高于类高于dom
```html
<div class="DIV">
	<span class="SPAN">测试</span>
</div>
<style type="text/css">
	/*优先级最低*/
	div span{
		background:orange;
	}
/****下面3种优先级等同位置靠后的生效*****/
	span.SPAN{
		background:pink;
	}

	.DIV span{
		background:gray;
	}

	div .SPAN{
		background:green;
	}
/********************************/
</style>
```
