### ISSUE TITLE
清除浮动总结

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/CSS#12]
# 姜维老师推荐版本
- clearfix为父元素
```css
.clearfix:before,
.clearfix:after{
	content:" ";
	display:table;
}

.clearfix:after{
	clear:both;
}
```
