### ISSUE TITLE
inline-block元素之间产生的空隙原因

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/CSS#13]
# 设置成inline-block的元素
- 原因是因为换行符产生的空元素。
![image](https://cloud.githubusercontent.com/assets/18028533/21087066/60c69100-c05d-11e6-9d48-cf4b38352523.png)
- dom结构
```html
	<ul>
		<li>登陆</li><li>快速注册</li>
		<li>关于</li>
		<li>帮助</li>
		<li>APP下载</li>
	</ul>
```
- 样式
```css
		ul li {
			/*在没有浮动的情况下才出现*/
			/*float:left;*/
			display: inline-block;
			width:70px;
			height:20px;
			background:orange;
			border:1px solid black;
		}
```

# 解决办法

1. 删除换行符
2. 加margin-left:-3px
3. 将父元素（ul）的字符大小设置成`font-size:0px;`再将子元素（li）设置成`font-size:16px;`->有副作用
4. 将li写到节点下方

```html
	<ul>
		<li>登陆
		</li><li>快速注册
		</li><li>关于
		</li><li>帮助
		</li><li>APP下载</li>
	</ul>
```
5. 标签不闭合，浏览器会自动补全，同时不会有间隙
```html
	<ul>
		<li>登陆
		<li>快速注册
		<li>关于
		<li>帮助
		<li>APP下载
	</ul>
```
6.借助注释
```html
<ul>
		<li>登陆</li><li>快速注册</li>
		<li>关于</li><!--
		--><li>帮助</li><!--
		--><li>APP下载</li>
	</ul>
```
![image](https://cloud.githubusercontent.com/assets/18028533/21087222/ba4b0ad4-c05e-11e6-84eb-aa301f5075e2.png)

# inline-block兄弟元素之间不对齐
- 如果其中一个兄弟元素有填充内容，另外一个没有，那就会造成不对齐，而且有个奇怪的现象：字的行数一定要相同，才能对齐。
- 解决方法是给child类加`vertical-align:top;`
![image](https://cloud.githubusercontent.com/assets/18028533/21217111/8777089a-c2e5-11e6-8894-c759e13f41a3.png)

```html
<div class="cont">
	<div class="child"></div>
	<div class="child">123</div>
</div> 
<style type="text/css">
.cont{
	width:500px;
	height:400px;
	border:1px solid gray;
}
.child{
	width:100px;
	height:200px;
	display:inline-block;
	border:1px solid orange;
	/*解决方法*/
	/*vertical-align:top;*/
}
</style>
```
