### ISSUE TITLE
适用于webkit特殊样式

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/CSS#16]
```css
//去掉webkit的滚动条——display: none;
//其他参数
::-webkit-scrollba //滚动条整体部分
::-webkit-scrollbar-thumb   //滚动条内的小方块
::-webkit-scrollbar-track   //滚动条轨道
::-webkit-scrollbar-button  //滚动条轨道两端按钮
::-webkit-scrollbar-track-piece  //滚动条中间部分，内置轨道
::-webkit-scrollbar-corner       //边角，两个滚动条交汇处
::-webkit-resizer            //两个滚动条的交汇处上用于通过拖动调整元素大小的小控件

	/* 滚动条样式demo */
	::-webkit-scrollbar { width:7px;border-radius:5px;height:10px;}/* 滚动条整体部分 */
	::-webkit-scrollbar-track { background-color:#324157;width:7px; }/* 滚动条轨道 */
	::-webkit-scrollbar-thumb { background-color: rgb(110, 114, 121);width:7px;height:10px; border-radius:10px;}/* //滚动条内的小方块 */
	::-webkit-scrollbar-thumb:hover {background-color:#a5b2c4;}
 
// 禁止长按链接与图片弹出菜单
a,img { -webkit-touch-callout: none }    
 
// 禁止ios和android用户选中文字
html,body {-webkit-user-select:none; user-select: none; }
 
// 改变输入框placeholder的颜色值
::-webkit-input-placeholder { /* WebKit browsers */
color: #999; }
:-moz-placeholder { /* Mozilla Firefox 4 to 18 */
color: #999; }
::-moz-placeholder { /* Mozilla Firefox 19+ */
color: #999; }
:-ms-input-placeholder { /* Internet Explorer 10+ */
color: #999; }
input:focus::-webkit-input-placeholder{ color:#999; }
 
// android上去掉语音输入按钮
input::-webkit-input-speech-button {display: none}
 
// 阻止windows Phone的默认触摸事件
/*说明：winphone下默认触摸事件事件使用e.preventDefault是无效的，可通过样式来禁用，如：*/
html { -ms-touch-action:none; } //禁止winphone默认触摸事件
```

# Demo
```css
  ::-webkit-scrollbar { width: 8px;border-radius:5px }/* Track & scroll thickness */

  ::-webkit-scrollbar-track { background-color:#ddd;border-radius:5px }/* Track color */

  ::-webkit-scrollbar-thumb { background-color: #333;width:5px; border-radius:5px}/* Scroll color */

  ::-webkit-scrollbar-thumb:hover { background-color: #000 }/* Scroll hover color */

  ::-webkit-scrollbar-thumb:active { background-color: #000 }/* Scroll click & drag color */
```
