### ISSUE TITLE
跨浏览器渐变方案

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/CSS#18]
## chrome,Safari
```css
div{
background: -webkit-gradient(linear, left top, left bottom, from(#ccc), to(#000));
}
/* 第二种写法 */
div{
background: -webkit-gradient(linear, 0 0, 0 100%, from(#ccc), to(#000));
}
```
## 对于Firefox3.6+
```css
div{
background: -moz-linear-gradient(top, #ccc, #000);
}
```
## IE 
```css
div{
 filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#cccccc', endColorstr='#000000');
}
```
