### ISSUE TITLE
水平垂直居中方案

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/CSS#19]
# 要点：
- 如果想要元素水平垂直居中，其必须有确定的宽高，因此在水平垂直居中元素之前先设宽高，因此最理想的状态是该元素为行内块元素`display:inline-block;`
# 一、页面元素为inline-block
> 注意box需要是块元素

```html
<div class="box" style="width:200px;height:200px;background:orange;">
		<button style="width:50px;height:50px;">按钮</button>
</div>
```
![image](https://cloud.githubusercontent.com/assets/18028533/22416517/f566d3ba-e709-11e6-8002-f5ea7b0f70e7.png)

## 方案一：用display: table-cell;
> 内部元素如果是display:block;则无效
```css
.box{
	display: table-cell;
	vertical-align:middle;
	text-align:center;
}
```
## 方案二：单纯flex布局
```css
.box{
    display: flex;
    justify-content:center;
    align-items:center;
}
```
## 方案三：flex与margin:auto;结合
```css
.box{
    display: flex;
}
button{margin: auto;}
```
## 方案四：绝对定位与0
```css
.box{
	position:relative;/*需要父元素定位*/
}
button{
  overflow: auto; 
  margin: auto; 
  position: absolute; 
  top: 0; left: 0; bottom: 0; right: 0; 
}
```
# 二、页面元素为block块状元素
```html
<div class="box" style="width:200px;height:200px;background:silver;">
	<div class="bt" style="width:50px;height:50px;background:green;"></div>
</div>
```
![image](https://cloud.githubusercontent.com/assets/18028533/22417141/b76e7a1e-e70d-11e6-8174-b765aa724059.png)

## 方案一：单纯flex布局
> flex布局会将block属性冲掉
```css
.box{
    display: flex;
    justify-content:center;
    align-items:center;
}
```
## 方案二：flex与margin:auto;结合
```css
.box{
    display: flex;
}
button{margin: auto;}
```
# 方案三：margin:auto与0
```css
.box{
	position:relative;/*需要父元素定位*/
}
.bt{
  overflow: auto; 
  margin: auto; 
  position: absolute; 
  top: 0; left: 0; bottom: 0; right: 0; 
}
```

# 如何垂直居中一个浮动元素？ 
```css
#div1{
	 background-color:#6699FF;
	 width:200px;
	 height:200px;
	 position: absolute; /*父元素需要相对定位*/
	 top: 50%;
	 left: 50%;
	 margin-top:-100px; /*二分之一的height，width*/
	 margin-left: -100px;
 }

/* 方法二:*/
#div1{
    width: 200px;
    height: 200px;
    background-color: #6699FF;
    margin:auto;
    position: absolute; /*父元素需要相对定位*/
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
}

/*  如何让一个img垂直水平居中 */
/*存放<img>的容器设置如下*/
#container{ 
	/*将内部元素按照单元格显示，因此可以垂直居中*/
	/*需要与vertical配合*/
    display:table-cell; 
    text-align:center;
    vertical-align:middle;
}
```
