### ISSUE TITLE
【Less】使用注意点

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/CSS#22]
1. 给input的placeholder改颜色写法

```css
.login-input input{
	width: 280px;
	height: 40px;
	margin: 0 auto;
	display: block;
	border: 1px solid #bdc3cd;
	&::-webkit-input-placeholder {
	    color: rgba(255,255,255,1);
	    opacity: 1;
	}
}

```

2. 添加普通伪类

```css
.class{
	&:focus {
		-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(127,198,246, 0.6);
		-moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(127,198,246, 0.6);
		box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(127,198,246, 0.6s);
	}
}

```
