### ISSUE TITLE
flexbox-多列布局写法（弹性布局）

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/CSS#3]
# 弹性布局Flex
> 写法(标准)

![image](https://cloud.githubusercontent.com/assets/18028533/22402813/88f933e2-e63e-11e6-871c-4c6103d4c1fa.png)
```html
<div class="div2">
	<div class="div21">123</div>
	<div class="div22">12312</div>
</div>
<style type="text/css">
	.div2{
		display: flex;width:300px;
		height:300px;background:pink;
	}
	.div21 {flex:2;    /* 5分之2*/background:gray;}
	.div22 {flex:3;  /*5分之3*/background:yellow;}
</style>
```

> 写法：Flex混合划分

![image](https://cloud.githubusercontent.com/assets/18028533/22770690/3e1641c0-eecd-11e6-9c75-6d9c9f0594e2.png)

```html
<div class="div2">
    <div class="div21">123</div>
    <div class="div22">12312</div>
    <div class="div33"></div>
</div>
<style type="text/css">
    .div2{
        display: flex; width:300px;
        height:300px; background:pink;
    }
    .div21 {
        flex:2;    /* 5分之2*/ background:gray;
    }
    .div22 {
        flex:3;  /*5分之3*/ background:yellow;
    }
    .div33 {
        background:orange; width:100px;
    }
</style>
```
>子元素总宽度>容器宽度

-  flex容器子元素如果全部是像素宽度，而且超出了flex容器的宽度是不会溢出或者换行的.会进行等比划分，适用于移动端响应式样式的排版。

![image](https://cloud.githubusercontent.com/assets/18028533/22770921/b6c720de-eece-11e6-8d92-71a32a01f64e.png)

```html
<div class="div2">
    <div class="div21">123</div>
    <div class="div22">12312</div>
    <div class="div33"></div>
</div>
<style type="text/css">
    .div2{display: flex;background:pink;
         width:300px;height:300px;}
    .div21 {background:gray;width:300px;}
    .div22 {width:300px;background:yellow;}
    .div33 {background:orange;width:100px;}
</style>
```

> 子元素总宽度<容器宽度

- 效果为左浮动，添加`justify-content:center`进行水平居中
![image](https://cloud.githubusercontent.com/assets/18028533/22771265/b1e76784-eed0-11e6-84eb-ab1e473dac9f.png)

```html
<div class="div2">
    <div class="div21">123</div>
    <div class="div22">12312</div>
    <div class="div33"></div>
</div>
<style type="text/css">
    .div2{display: flex;border:1px solid black;
         width:300px;height:300px;
         /*水平居中*/
         justify-content:center;}
    .div21 {background:gray;width:50px;}
    .div22 {background:yellow;width:50px;}
    .div33 {background:orange;width:50px;}
</style>
```

 # box-flex 
> 目前没有浏览器支持 box-flex 属性。box-flex 属性规定框的子元素是否可伸缩其尺寸。所以都需要加前缀

![image](https://cloud.githubusercontent.com/assets/18028533/22402867/d77cac86-e640-11e6-9ac0-6622d302d762.png)

``` html
<div style="width:400px;height:500px;background:green;">
<form style="display:block;display:-webkit-box">
    <span style="background:blue;-webkit-box-flex:1;display: block">11111</span>
    <span style="background:pink;-webkit-box-flex:2;display:block">22222</span>
</form>
</div>
```
- 两者效果类似box-flex是老版本，新版本统一为display:flex;

# 弹性盒布局模型的浏览器前缀形式
- [添加浏览器前缀](http://autoprefixer.github.io/)

## 兼容性
- IOS可以使用最新的flex布局
- android4.4以下，只能兼容旧版本第一版的flexbox布局(-webkit-box)
- android4.4及以上，可以使用第二版的flex布局(-webkit-flex)

<table>
    <tr>
        <td>第一版</td>
        <td>第二版</td>
        <td>标准版</td>
    </tr>
    <tr>
        <td>display:-webkit-box;</td>
        <td>display:-webkit-flex;</td>
        <td>display:flex;</td>
    </tr>
    <tr>
        <td>-webkit-flex-box:1;</td>
        <td>-webkit-flex:1;</td>
        <td>flex:1;</td>
    </tr>
    <tr>
        <td>box-pack:center;</td>
        <td>justify-content:center;</td>
        <td>justify-content:center;</td>
    </tr>
    <tr>
        <td>box-align:center;</td>
        <td>align-items:center;</td>
        <td>align-items:center;</td>
    </tr>
</table>

```css
.flex-container {
 display: -webkit-box;/*09年*/
 display: -moz-box;/*09年*/
 display: -ms-flexbox;/*09年*/
 display: -webkit-flex;/*12年*/
 display: flex;/*标准版*/
}

.flex-item {
 -webkit-box-flex: auto;

-moz-box-flex: auto;
-webkit-flex: auto;
-ms-flex: auto;
 flex: auto;
}

.flex-item {
 -webkit-box-ordinal-group: 1;
 -moz-box-ordinal-group: 1;
 -ms-flex-order: 1;
 -webkit-order: 1;
 order: 1;
}
```
# 弹性图片

- 对于图片的可伸缩性需要使用`max-width:100%`,需要用百分比布局，而不能使用`max-width:100px;`
