### ISSUE TITLE
justify-content:center 居中demo

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/CSS#4]
# CSS3样式居中
经过测试，display:-webkit-flex 有float:left的效果。

``` css
<style type="text/css">
  .div2{
    background:green;
    height:200px;
    width:200px;
    display:-webkit-flex;   /*别写成display:-webkit-box */
    margin-left:200px;
  }
  .p1{
    width:50px;
    height:50px;
    background:red;

  }
</style>
```

节点  a标签自动变成了display:block;可以设置宽高

``` html
    <div class="div2" style="justify-content:center;">
        <a class="p1" href="">123</a>
        <a class="p1" href="">456</a>
    </div>
```
# 弹窗组件中的居中
```css
/*	水平，垂直居中方式一*/
	display:-webkit-box;
	-webkit-box-pack:center;/*水平居中*/
	-webkit-box-align:center;/*垂直居中*/
```
```css

	/*方案二*/
	display:-webkit-flex;
	-webkit-justify-content:center;
	-webkit-align-items:center;
```
