### ISSUE TITLE
css样式初始化

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/CSS#6]
# 自己总结的cssReset
``` css
    /*div，span是没有margin,padding的*/
    body,button,dd,dl,dt,fieldset,form,h1,h2,h3,h4,h5,h6,hr,input,legend,li,ol,p,pre,td,textarea,th,ul {margin: 0;padding:0;}
    h1,h2,h3,h4,h5,h6 {font-size: 100%}
    body,button,input,select,textarea {font-size:12px;font-family:;}
    address,cite,dfn,em,var,i{font-style: normal;}
    strong {font-weight:normal;}
    small {font-size: 12px}
    ol,ul {list-style: none}
    a {text-decoration: none}
    a:hover {text-decoration: underline}
    legend {color: #000}
    button,input,select,textarea {font-size: 100%}
    table {border-collapse: collapse;border-spacing: 0}
```
# 传统版的css reset
```css
/* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
 a {
        text-decoration: none
}
```
