### ISSUE TITLE
IE6，7，8兼容样式写法。

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/CSS#8]
# IE专用前缀
> 拿color:#000; 这个一个样式为例：
```css
	.ClASS{
		_color:#000 ; /*IE6专用样式：  _ (低等)*/
	}

	.ClASS{
		#color:#000; /*IE7专用样式： # （形状像）*/
	}

	.ClASS{
		*color:#000; /*IE6、7共用: **/
	}

/*********************************************************************************************/
       .ClASS{
		color:#ooo\0; /*IE8专用样式： \0 （\0都有圈圈）*/
	}
	.ClASS{
		color:#000\9; /*IE6、7、8共用：: \9*/
	}
```
# 

_经测试，在样式后加\0或\9，IE9也一样可以解析，所以，这不能算是专用样式。_

# IE透明度
```html
<!--DOM-->
<div id="ID" class="CLASS" style="color:black;">你好</div>
```
> 针对ie8的透明效果
```css
.CLASS {
    filter: alpha(opacity=50);/* ie8以及以上才有效*/
}
```
> 如果想让ie7也有透明效果则需要对元素设定宽高
```css
    .CLASS { 
		background:blue;
		filter: alpha(opacity=50); 
		width:100px;/*针对ie7透明度*/
		height:50px;/*针对ie7透明度*/
　　}
```
> 在IE6中设置PNG图片的透明效果
```

    　　.classname {

    　　　　background: url(image.png);

    　　　　_background: none;

    　　　　_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader
    　　　　　　　　(src='image.png', sizingMethod='crop');

    　　}

```
